site_name: Heo Geo 
site_url: https://heo-geo.github.io

theme:
  name: material
  icon:
    logo: material/code-braces
  palette:
    - scheme: slate

extra_css:
  - stylesheets/extra.css

copyright: Copyright &copy; 2026 Heorhii Terentiev

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/heo-geo
      name: GitHub
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/heorhii-terentiev/
      name: LinkedIn

nav:
  - Home: index.md
  - About: about.md
  - Contact: contact.md
  - Talks:
    - Overview: talks/index.md
    - "2025":
      - VaanTalk — Prototyping & Communication: talks/2025/vaantalk-key-to-success.md
  - Shopify:
    - Articles:
      - Intro to the Headless Approach: shopify/intro-to-the-shopify-headless-approach.md
      - Who's Who in Shopify Partners: shopify/who-is-who-in-shopify-partner-ecosystem.md
      - Sharing Preview Links: shopify/sharing-preview-links-during-theme-development.md
      - Shopify Preview Bar: shopify/shopify-preview-bar.md
      - Accessing Metaobjects in Liquid: shopify/accessing-metaobjects-using-liquid.md
    - Bookmarks:
      - Frontend: bookmarks/shopify/front.md
      - Backend: bookmarks/shopify/back.md
      - Learning Resources: bookmarks/shopify/learning-resources.md
      - News Sources: bookmarks/shopify/shopify-news-sources.md
    - Interview Questions:
      - Ajax API: bookmarks/shopify/interview-questions/shopify-ajax-api.md
      - Development Flow: bookmarks/shopify/interview-questions/development-flow.md
      - Liquid — Practice: bookmarks/shopify/interview-questions/liquid-practice.md
      - Liquid — Theory: bookmarks/shopify/interview-questions/liquid-theory.md
      - Metafields & Metaobjects: bookmarks/shopify/interview-questions/metafields-metaobjects.md
      - Navigation, Filtering & Search: bookmarks/shopify/interview-questions/navigation-filtering-search-product-recommendation.md
      - Order Additional Info: bookmarks/shopify/interview-questions/order-additional-info.md
      - Section Rendering API: bookmarks/shopify/interview-questions/section-rendering-api.md
      - SEO: bookmarks/shopify/interview-questions/shopify-seo.md
      - Shopify Plus: bookmarks/shopify/interview-questions/shopify-plus-theory.md
      - Theme Architecture: bookmarks/shopify/interview-questions/theme-architecture.md
  - General Bookmarks:
    - Front-end: bookmarks/front-end.md
    - Back-end: bookmarks/back-end.md
    - 3D in Web: bookmarks/3d-in-web.md
